### ISSUE TITLE
please add Left - Left and Right-Right options to the 

### ISSUE THREAD

**Issue by DeadlyKitten37** [BurnySc2/BurnysTSBC#11]
please add an option the do same direction stackers (examples in image), these are nice because they allow departing from and going to the same side, which is more difficult and takes more space on the LR and RL variants 

![image](https://user-images.githubusercontent.com/53106272/86076613-9e547180-ba47-11ea-892e-e6703d43e8f7.png)

**Comment by BurnySc2** [comment]
Yup I can add that, however I will not be modifying the mod, but rather improve the web-version of the mod which can be found here: https://burnysc2.github.io/Factorio/Tools/BurnysTSBC/

I'm not sure when I will have time to add this feature though, it might take a couple months.

**Comment by BurnySc2** [comment]
I've been remaking the website and Left-Left and Right-Right stackers are now available:

https://burnysc2.github.io/Factorio-Train-Station-Blueprint-Creator/
